<MyBoxLayout>
    BoxLayout:
        #orientation: "horizontal"
        orientation: "vertical"
        size: root.width, root.height

        spacing: 20
        padding: 50

        Button:
            text: "Hello World"


        Button:
            text: "Goodbye World"

        Button:
            text: "I Am The World"
            pos_hint: {'center_x': .5}
            size_hint: (None, None)
            width: 200
            height: 50